#!/bin/bash

# ================================================================
# Aim:  This script displays the contents of README.txt.
#       - If run with "--version", it prints only the first 3 lines.
#       - If run without arguments, it prints the whole file.
# ================================================================

# If "--version" argument is passed
if [[ "$1" == "--version" ]]; then
    # Using git to get the last commit date as version info
    echo "Personal Bash Commands Package (mycmd)"
    cd "$MYCMD"  # Change to the package directory for git command to work
    echo "Version: $(git log -1 --date=format-local:"%b %d, %Y" --format="%cd")"
    echo -e "\033[32mTry 'mycmd --help' for more information.\033[0m"
elif [[ "$1" == "--help" ]]; then
    # Print the entire README.txt file
    cat "$MYCMD/README.txt"
else
    echo -e "\033[1;35mAvailable Commands in this package are:\033[0m"
    find "$MYCMD" -maxdepth 1 -type f ! -name "*.*" -printf "    > %f\n"
    echo -e "\033[32mTry 'mycmd --help' for more information.\033[0m"
fi
